### ISSUE TITLE
docker做镜像后，impot hanlp失败

### ISSUE THREAD

**Issue by Voccoo** [WalterInSH/hanlp-jupyter-docker#2]
ubuntu 16.4.
通过dockerfile安装后，在jupyter中import hanlp 无法导入。
提示信息“运行失败”

是因为ubuntu版本低的问题嘛？

**Comment by WalterInSH** [comment]
@Voccoo 抱歉回复晚了，能贴一下完整的报错信息吗？
ubuntu 16.4是指宿主机，是吗？

**Comment by Voccoo** [comment]
这个问题我自己处理过了。应该还是宿主机器对于TF2.0 或者说1.5版本以上的不支持导致的。
从而无法完成相关包的导入初始化。

docker镜像做的hanlp我已经自己打包出来了，很好用，很准确。
大佬牛逼！
